# Generated by Django 4.1.7 on 2023-02-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0002_rename_orderitems_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
