# Generated by Django 4.1.7 on 2023-02-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0003_alter_menuitems_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
